import type { ModelInfo } from "@/shared/types";

export const GOOGLE_MODELS: ModelInfo[] = [
  // --- Latest ---
  {
    id: "gemini-pro-latest",
    name: "Gemini Pro Latest",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "stable",
    description: "Latest release of Gemini Pro (alias).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-flash-latest",
    name: "Gemini Flash Latest",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "stable",
    description: "Latest release of Gemini Flash (alias).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-flash-lite-latest",
    name: "Gemini Flash-Lite Latest",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "stable",
    description: "Latest release of Gemini Flash-Lite (alias).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Gemini 3.1 / 3 (Preview) ---
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description:
      "Preview of Gemini 3.1 Pro (Jan 2026). High reasoning capabilities.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Gemini 3.1 Pro Preview optimized for custom tool usage.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "preview",
    description:
      "Preview of Gemini 3.1 Flash Lite (Mar 2026). Fast and efficient.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description:
      "Preview of Gemini 3 Pro (Nov 2025). High reasoning capabilities.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Preview of Gemini 3 Flash (Dec 2025). Fast and efficient.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Gemini 2.5 (Stable) ---
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "stable",
    description:
      "Stable release of Gemini 2.5 Pro. High reasoning, multimodal, and thinking capabilities.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
    isRecommended: true,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "stable",
    description:
      "Stable version of Gemini 2.5 Flash. Fast, multimodal, supports up to 1 million tokens.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
    isRecommended: true,
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "stable",
    description:
      "Stable version of Gemini 2.5 Flash-Lite. Cost-effective and fast.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
    isRecommended: true,
  },

  // --- Gemini 2.0 (Legacy) ---
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "legacy",
    description: "Gemini 2.0 Flash.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "legacy",
    description: "Gemini 2.0 Flash-Lite.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    id: "gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash 001",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "legacy",
    description: "Stable version of Gemini 2.0 Flash 001.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    id: "gemini-2.0-flash-lite-001",
    name: "Gemini 2.0 Flash-Lite 001",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "legacy",
    description: "Stable version of Gemini 2.0 Flash-Lite 001.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },

  // --- Gemma 4 Models ---
  {
    id: "gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B IT",
    provider: "google",
    family: "gemma",
    stage: "stable",
    description: "Gemma 4 26B A4B IT Instruction Tuned.",
    contextWindow: { input: 262_144, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: false,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    provider: "google",
    family: "gemma",
    stage: "stable",
    description: "Gemma 4 31B IT Instruction Tuned.",
    contextWindow: { input: 262_144, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: false,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Nano Banana ---
  {
    id: "gemini-3.1-flash-image-preview",
    name: "Nano Banana 2",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 3.1 Flash Image Preview (Nano Banana 2).",
    contextWindow: { input: 65_536, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: false,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3-pro-image-preview",
    name: "Gemini 3 Pro Image (Nano Banana)",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Gemini 3 Pro Image Preview (Nano Banana Pro).",
    contextWindow: { input: 131_072, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "nano-banana-pro-preview",
    name: "Nano Banana Pro Preview",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Nano Banana Pro (Gemini 3 Pro Image) Preview.",
    contextWindow: { input: 131_072, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-image",
    name: "Nano Banana Flash Preview",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Preview Image (Nano Banana).",
    contextWindow: { input: 32_768, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Imagen ---
  {
    id: "imagen-4.0-generate-001",
    name: "Imagen 4",
    provider: "google",
    family: "imagen",
    stage: "stable",
    description: "Vertex served Imagen 4.0 model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "imagen-4.0-ultra-generate-001",
    name: "Imagen 4 Ultra",
    provider: "google",
    family: "imagen",
    stage: "stable",
    description: "Vertex served Imagen 4.0 Ultra model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "imagen-4.0-fast-generate-001",
    name: "Imagen 4 Fast",
    provider: "google",
    family: "imagen",
    stage: "stable",
    description: "Vertex served Imagen 4.0 Fast model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },

  // --- Veo ---
  {
    id: "veo-3.1-generate-preview",
    name: "Veo 3.1 Preview",
    provider: "google",
    family: "veo",
    stage: "preview",
    description: "Veo 3.1 video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.1-fast-generate-preview",
    name: "Veo 3.1 Fast Preview",
    provider: "google",
    family: "veo",
    stage: "preview",
    description: "Veo 3.1 Fast video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.1-lite-generate-preview",
    name: "Veo 3.1 lite",
    provider: "google",
    family: "veo",
    stage: "preview",
    description: "Veo 3.1 lite video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.0-generate-001",
    name: "Veo 3",
    provider: "google",
    family: "veo",
    stage: "stable",
    description: "Veo 3 video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.0-fast-generate-001",
    name: "Veo 3 Fast",
    provider: "google",
    family: "veo",
    stage: "stable",
    description: "Veo 3 Fast video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-2.0-generate-001",
    name: "Veo 2",
    provider: "google",
    family: "veo",
    stage: "stable",
    description: "Veo 2 video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },

  // --- Gemini 3.1 / 2.5 Audio Specialized (Audio/TTS) ---
  {
    id: "gemini-3.1-flash-tts-preview",
    name: "Gemini 3.1 Flash TTS Preview",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 3.1 Flash customized for Text-to-Speech tasks.",
    contextWindow: { input: 8_192, output: 16_384 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3.1-flash-live-preview",
    name: "Gemini 3.1 Flash Live Preview",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 3.1 Flash Live Preview.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: false,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-native-audio-latest",
    name: "Gemini 2.5 Flash Native Audio",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "stable",
    description: "Gemini 2.5 Flash optimized for native audio interaction.",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-pro-preview-tts",
    name: "Gemini 2.5 Pro TTS",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Gemini 2.5 Pro customized for Text-to-Speech tasks.",
    contextWindow: { input: 8_192, output: 16_384 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-preview-tts",
    name: "Gemini 2.5 Flash TTS",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash customized for Text-to-Speech tasks.",
    contextWindow: { input: 8_192, output: 16_384 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Lyria Previews ---
  {
    id: "lyria-3-clip-preview",
    name: "Lyria 3 Clip Preview",
    provider: "google",
    family: "lyria",
    stage: "preview",
    description: "Lyria 3 30s model Preview.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: true,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "lyria-3-pro-preview",
    name: "Lyria 3 Pro Preview",
    provider: "google",
    family: "lyria",
    stage: "preview",
    description: "Lyria 3 Pro Preview.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: true,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Audio / TTS Preview Variants ---
  {
    id: "gemini-2.5-flash-native-audio-preview-12-2025",
    name: "Gemini 2.5 Flash Native Audio Preview Dec 2025",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Native Audio Preview (Dec 2025).",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-native-audio-preview-09-2025",
    name: "Gemini 2.5 Flash Native Audio Preview Sep 2025",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Native Audio Preview (Sep 2025).",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // Domain specializations preview
  {
    id: "deep-research-max-preview-04-2026",
    name: "Deep Research Max Preview",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Preview release (April 21st, 2026) of Deep Research Max.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "deep-research-preview-04-2026",
    name: "Deep Research Preview",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Preview release (April 21st, 2026) of Deep Research.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-robotics-er-1.6-preview",
    name: "Gemini Robotics-ER 1.6 Preview",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Gemini Robotics-ER 1.6 Preview.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-computer-use-preview-10-2025",
    name: "Gemini 2.5 Computer Use",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Gemini 2.5 Computer Use Preview 10-2025.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Specialized / Utility ---
  {
    id: "gemini-embedding-2",
    name: "Gemini Embedding 2",
    provider: "google",
    family: "gemini",
    stage: "stable",
    description: "Obtain a distributed representation of multimodal content.",
    contextWindow: { input: 8_192, output: 1 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: true,
    },
  },
  {
    id: "gemini-embedding-2-preview",
    name: "Gemini Embedding 2 Preview",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Obtain a distributed representation of multimodal content.",
    contextWindow: { input: 8_192, output: 1 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: true,
    },
  },
  {
    id: "gemini-embedding-001",
    name: "Gemini Embedding 001",
    provider: "google",
    family: "gemini",
    stage: "stable",
    description: "Gemini Embedding Model 001.",
    contextWindow: { input: 2_048, output: 1 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: true,
    },
  },
  {
    id: "aqa",
    name: "Attributed Question Answering",
    provider: "google",
    family: "other",
    stage: "stable",
    description: "Model for grounded question answering.",
    contextWindow: { input: 7_168, output: 1_024 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 0.2,
      topP: 1,
      topK: 40,
    },
  },
];
