import type { ModelInfo } from "@/types";

export const GOOGLE_MODELS: ModelInfo[] = [
  // --- Latest ---
  {
    id: "gemini-pro-latest",
    name: "Gemini Pro Latest",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "stable",
    description: "Latest release of Gemini Pro (alias).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-flash-latest",
    name: "Gemini Flash Latest",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "stable",
    description: "Latest release of Gemini Flash (alias).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-flash-lite-latest",
    name: "Gemini Flash-Lite Latest",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "stable",
    description: "Latest release of Gemini Flash-Lite (alias).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Gemini 2.5 (Stable) ---
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "stable",
    description:
      "Stable release of Gemini 2.5 Pro. High reasoning, multimodal, and thinking capabilities.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
    isRecommended: true,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "stable",
    description:
      "Stable version of Gemini 2.5 Flash. Fast, multimodal, supports up to 1 million tokens.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
    isRecommended: true,
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "stable",
    description:
      "Stable version of Gemini 2.5 Flash-Lite. Cost-effective and fast.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
    isRecommended: true,
  },

  // --- Gemini 3 (Preview) ---
  {
    id: "gemini-3-pro-preview-11-2025",
    name: "Gemini 3 Pro Preview",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description:
      "Preview of Gemini 3 Pro (Nov 2025). High reasoning capabilities.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-3-flash-preview-12-2025",
    name: "Gemini 3 Flash Preview",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Preview of Gemini 3 Flash (Dec 2025). Fast and efficient.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Gemini 2.0 (Legacy) ---
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "legacy",
    description: "Gemini 2.0 Flash.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    provider: "google",
    family: "gemini",
    tier: "lite",
    stage: "legacy",
    description: "Gemini 2.0 Flash-Lite.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },

  // --- Gemma 3 Models ---
  {
    id: "gemma-3-1b-it",
    name: "Gemma 3 1B",
    provider: "google",
    family: "gemma",
    tier: "nano",
    stage: "stable",
    description: "Gemma 3 1B Instruction Tuned.",
    contextWindow: { input: 32_768, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemma-3-4b-it",
    name: "Gemma 3 4B",
    provider: "google",
    family: "gemma",
    stage: "stable",
    description: "Gemma 3 4B Instruction Tuned.",
    contextWindow: { input: 32_768, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemma-3-12b-it",
    name: "Gemma 3 12B",
    provider: "google",
    family: "gemma",
    stage: "stable",
    description: "Gemma 3 12B Instruction Tuned.",
    contextWindow: { input: 32_768, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemma-3-27b-it",
    name: "Gemma 3 27B",
    provider: "google",
    family: "gemma",
    stage: "stable",
    description: "Gemma 3 27B Instruction Tuned.",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Gemma 3 Nano (e-variants) ---
  {
    id: "gemma-3n-e4b-it",
    name: "Gemma 3n E4B",
    provider: "google",
    family: "gemma",
    tier: "nano",
    stage: "stable",
    description: "Gemma 3n E4B Instruction Tuned.",
    contextWindow: { input: 8_192, output: 2_048 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemma-3n-e2b-it",
    name: "Gemma 3n E2B",
    provider: "google",
    family: "gemma",
    tier: "nano",
    stage: "stable",
    description: "Gemma 3n E2B Instruction Tuned.",
    contextWindow: { input: 8_192, output: 2_048 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Nano Banana ---
  {
    id: "gemini-3-pro-image-preview",
    name: "Gemini 3 Pro Image (Nano Banana)",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Gemini 3 Pro Image Preview (Nano Banana Pro).",
    contextWindow: { input: 131_072, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "nano-banana-pro-preview",
    name: "Nano Banana Pro Preview",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Nano Banana Pro (Gemini 3 Pro Image) Preview.",
    contextWindow: { input: 131_072, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-image",
    name: "Nano Banana Flash Preview",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Preview Image (Nano Banana).",
    contextWindow: { input: 32_768, output: 32_768 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Imagen ---
  {
    id: "imagen-4.0-generate-001",
    name: "Imagen 4",
    provider: "google",
    family: "imagen",
    stage: "stable",
    description: "Vertex served Imagen 4.0 model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "imagen-4.0-ultra-generate-001",
    name: "Imagen 4 Ultra",
    provider: "google",
    family: "imagen",
    stage: "stable",
    description: "Vertex served Imagen 4.0 Ultra model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "imagen-4.0-fast-generate-001",
    name: "Imagen 4 Fast",
    provider: "google",
    family: "imagen",
    stage: "stable",
    description: "Vertex served Imagen 4.0 Fast model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "imagen-4.0-generate-preview-06-06",
    name: "Imagen 4 Preview 06-06",
    provider: "google",
    family: "imagen",
    stage: "preview",
    description: "Imagen 4 Preview.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "imagen-4.0-ultra-generate-preview-06-06",
    name: "Imagen 4 Ultra Preview 06-06",
    provider: "google",
    family: "imagen",
    stage: "preview",
    description: "Imagen 4 Ultra Preview.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },

  // --- Veo ---
  {
    id: "veo-3.0-generate-001",
    name: "Veo 3",
    provider: "google",
    family: "veo",
    stage: "stable",
    description: "Veo 3 video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.0-fast-generate-001",
    name: "Veo 3 Fast",
    provider: "google",
    family: "veo",
    stage: "stable",
    description: "Veo 3 Fast video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-2.0-generate-001",
    name: "Veo 2",
    provider: "google",
    family: "veo",
    stage: "stable",
    description: "Veo 2 video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.1-generate-preview",
    name: "Veo 3.1 Preview",
    provider: "google",
    family: "veo",
    stage: "preview",
    description: "Veo 3.1 video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },
  {
    id: "veo-3.1-fast-generate-preview",
    name: "Veo 3.1 Fast Preview",
    provider: "google",
    family: "veo",
    stage: "preview",
    description: "Veo 3.1 Fast video generation model.",
    contextWindow: { input: 480, output: 8_192 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
  },

  // Domain specializations preview
  {
    id: "deep-research-pro-preview-12-2025",
    name: "Deep Research Pro Preview",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description:
      "Deep Research Pro Preview (Dec 2025). Specialized for deep research.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-robotics-er-1.5-preview",
    name: "Gemini Robotics-ER 1.5 Preview",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Gemini Robotics-ER 1.5 Preview.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-computer-use-preview-10-2025",
    name: "Gemini 2.5 Computer Use",
    provider: "google",
    family: "gemini",
    stage: "preview",
    description: "Gemini 2.5 Computer Use Preview 10-2025.",
    contextWindow: { input: 131_072, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Specialized / Utility ---
  {
    id: "gemini-embedding-001",
    name: "Gemini Embedding 001",
    provider: "google",
    family: "gemini",
    stage: "stable",
    description: "Gemini Embedding Model 001.",
    contextWindow: { input: 2_048, output: 1 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: false, // Embedding only
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: true,
    },
  },
  {
    id: "aqa",
    name: "Attributed Question Answering",
    provider: "google",
    family: "other",
    stage: "stable",
    description: "Model for grounded question answering.",
    contextWindow: { input: 7_168, output: 1_024 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 0.2,
      topP: 1,
      topK: 40,
    },
  },

  // --- Gemini 2.5 Audio Specialized (Audio/TTS) ---
  {
    id: "gemini-2.5-flash-native-audio-latest",
    name: "Gemini 2.5 Flash Native Audio",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "stable",
    description: "Gemini 2.5 Flash optimized for native audio interaction.",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-pro-preview-tts",
    name: "Gemini 2.5 Pro TTS",
    provider: "google",
    family: "gemini",
    tier: "pro",
    stage: "preview",
    description: "Gemini 2.5 Pro customized for Text-to-Speech tasks.",
    contextWindow: { input: 8_192, output: 16_384 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-preview-tts",
    name: "Gemini 2.5 Flash TTS",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash customized for Text-to-Speech tasks.",
    contextWindow: { input: 8_192, output: 16_384 },
    capabilities: {
      imageInput: false,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: false,
      codeExecution: false,
      systemInstruction: false,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },

  // --- Experimental / Other ---
  {
    id: "gemini-exp-1206",
    name: "Gemini Experimental 1206",
    provider: "google",
    family: "gemini",
    stage: "experimental",
    description: "Experimental release (March 25th, 2025) of Gemini 2.5 Pro.",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.0-flash-exp-image-generation",
    name: "Gemini 2.0 Flash (Image Gen) Exp",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "experimental",
    description:
      "Experimental Gemini 2.0 Flash with image generation capabilities.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: false,
      audioInput: false,
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: false,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },

  // --- Gemini 2.5 / 2.0 (Specific Versions) ---
  {
    id: "gemini-2.5-flash-preview-09-2025",
    name: "Gemini 2.5 Flash Preview Sep 2025",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Preview (Sep 2025).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-lite-preview-09-2025",
    name: "Gemini 2.5 Flash-Lite Preview Sep 2025",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash-Lite Preview (Sep 2025).",
    contextWindow: { input: 1_048_576, output: 65_536 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash 001",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "legacy",
    description: "Stable version of Gemini 2.0 Flash 001.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    id: "gemini-2.0-flash-lite-001",
    name: "Gemini 2.0 Flash-Lite 001",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "legacy",
    description: "Stable version of Gemini 2.0 Flash-Lite 001.",
    contextWindow: { input: 1_048_576, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: false,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: false,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 40,
    },
  },

  // --- Audio / TTS Preview Variants ---
  {
    id: "gemini-2.5-flash-native-audio-preview-12-2025",
    name: "Gemini 2.5 Flash Native Audio Preview Dec 2025",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Native Audio Preview (Dec 2025).",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
  {
    id: "gemini-2.5-flash-native-audio-preview-09-2025",
    name: "Gemini 2.5 Flash Native Audio Preview Sep 2025",
    provider: "google",
    family: "gemini",
    tier: "flash",
    stage: "preview",
    description: "Gemini 2.5 Flash Native Audio Preview (Sep 2025).",
    contextWindow: { input: 131_072, output: 8_192 },
    capabilities: {
      imageInput: true,
      videoInput: true,
      audioInput: true,
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      speechGeneration: true,
      functionCalling: true,
      codeExecution: true,
      systemInstruction: true,
      thinking: true,
      embedding: false,
    },
    defaultParameters: {
      temperature: 1,
      topP: 0.95,
      topK: 64,
    },
  },
];
